[workspace]
members = [
    "falcon-sys",
    "falcon",
    "stellar-pq/contracts/soroban-falcon-verifier",
    "stellar-pq/contracts/soroban-falcon-smart-account",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Alexandre Roque"]
